name: "0 Force deployment"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version you want to release."
        required: true

jobs:
  run:
    name: "Draft a new release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Show current branch
        run: git rev-parse --abbrev-ref HEAD
