name: "0 Force deployment"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment to deploy"
        required: true

jobs:
  run:
    name: "Draft a new release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Show current branch
        run: |
          git rev-parse --abbrev-ref HEAD
          echo ${{ github.event.inputs.environment }}
