name: "3 PR tests"

on:
  pull_request:
    branches:
      - main
      - master
      - beta

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup
        run: yarn
      - name: Tests runner
        run: yarn test
