name: "docker build and push"

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push

        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: nicacioliveira/gactions-cicd-boilerplate:${{ github.sha }}
  k8s-manifest-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update values.yaml
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: "./k8s/nodeapi.yaml"
          propertyPath: "spec.template.spec.containers.name"
          value: nicacioliveira/gactions-cicd-boilerplate:${{ github.sha }}
          commitChange: true
          updateFile: true
