name: "docker build and push"

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push

        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: nicacioliveira/gactions-cicd-boilerplate:${{ github.sha }}

  k8s-manifest-update:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Change k8s container tag
        run: cd ./k8s/scripts && npm install && node ./containertag.replacer.js nicacioliveira/gactions-cicd-boilerplate nicacioliveira/gactions-cicd-boilerplate:${{ github.sha }}
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com
      - name: Commit deployment manifest files
        id: make-commit
        run: |
          git add .
          git commit --m "k8s deployment container updated: nicacioliveira/gactions-cicd-boilerplate:${{ github.sha }}"
      - name: Push changes
        run: git push origin master
